backend:
  name: github
  repo: alissonmgsantos/my_portfolio
  branch: develop
  site_domain: https://alissonmgsantos.netlify.app/

  # This line should *not* be indented
publish_mode: editorial_workflow

# This line should *not* be indented
media_folder: "static/assets/images" # Media files will be stored in the repo under images/uploads
public_folder: "/assets/images" # The src attribute for uploaded media will begin with /images/uploads


collections:
  - name: "user" # Used in routes, e.g., /admin/collections/blog
    label: "User" # Used in the UI
    folder: "posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in front matter
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Bio", name: "bio", widget: "string"}
      - {label: "Skills", name: "skills", widget: "code"}
      - {label: "Services", name: "services", widget: "code"}